const books=[["Genesis",50,"old"],["Exodus",40,"old"],["Leviticus",27,"old"],["Numbers",36,"old"],["Deuteronomy",34,"old"],["Joshua",24,"old"],["Judges",21,"old"],["Ruth",4,"old"],["1 Samuel",31,"old"],["2 Samuel",24,"old"],["1 Kings",22,"old"],["2 Kings",25,"old"],["1 Chronicles",29,"old"],["2 Chronicles",36,"old"],["Ezra",10,"old"],["Nehemiah",13,"old"],["Esther",10,"old"],["Job",42,"old"],["Psalms",150,"old"],["Proverbs",31,"old"],["Ecclesiastes",12,"old"],["Song of Solomon",8,"old"],["Isaiah",66,"old"],["Jeremiah",52,"old"],["Lamentations",5,"old"],["Ezekiel",48,"old"],["Daniel",12,"old"],["Hosea",14,"old"],["Joel",3,"old"],["Amos",9,"old"],["Obadiah",1,"old"],["Jonah",4,"old"],["Micah",7,"old"],["Nahum",3,"old"],["Habakkuk",3,"old"],["Zephaniah",3,"old"],["Haggai",2,"old"],["Zechariah",14,"old"],["Malachi",4,"old"],["Matthew",28,"new"],["Mark",16,"new"],["Luke",24,"new"],["John",21,"new"],["Acts",28,"new"],["Romans",16,"new"],["1 Corinthians",16,"new"],["2 Corinthians",13,"new"],["Galatians",6,"new"],["Ephesians",6,"new"],["Philippians",4,"new"],["Colossians",4,"new"],["1 Thessalonians",5,"new"],["2 Thessalonians",3,"new"],["1 Timothy",6,"new"],["2 Timothy",4,"new"],["Titus",3,"new"],["Philemon",1,"new"],["Hebrews",13,"new"],["James",5,"new"],["1 Peter",5,"new"],["2 Peter",3,"new"],["1 John",5,"new"],["2 John",1,"new"],["3 John",1,"new"],["Jude",1,"new"],["Revelation",22,"new"]];
const fileNames={"1 Samuel":"1Samuel","2 Samuel":"2Samuel","1 Kings":"1Kings","2 Kings":"2Kings","1 Chronicles":"1Chronicles","2 Chronicles":"2Chronicles","Song of Solomon":"SongofSolomon","1 Corinthians":"1Corinthians","2 Corinthians":"2Corinthians","1 Thessalonians":"1Thessalonians","2 Thessalonians":"2Thessalonians","1 Timothy":"1Timothy","2 Timothy":"2Timothy","1 Peter":"1Peter","2 Peter":"2Peter","1 John":"1John","2 John":"2John","3 John":"3John"};
const DATA_URL="https://raw.githubusercontent.com/aruljohn/Bible-kjv/master/";
const loadedBooks={};let currentBook="Genesis",currentChapter=1,currentDailyVerse;
const encouragements={peace:{title:"God Is Your Peace",verse:"Be still, and know that I am God.",reference:"Psalm 46:10",message:"Xyhime, you do not have to solve everything at once. Rest your heart in God's presence."},strength:{title:"God Will Strengthen You",verse:"Fear thou not; for I am with thee: be not dismayed; for I am thy God.",reference:"Isaiah 41:10",message:"You are not carrying today's weight alone."},anxiety:{title:"Give God Your Worries",verse:"Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.",reference:"Philippians 4:6",message:"Place each worry before God one at a time."},faith:{title:"Keep Trusting",verse:"Trust in the LORD with all thine heart; and lean not unto thine own understanding.",reference:"Proverbs 3:5",message:"You do not need to see the entire road to trust the One leading you."},love:{title:"You Are Loved",verse:"We love him, because he first loved us.",reference:"1 John 4:19",message:"Before achievements or expectations, remember that you are deeply loved."},gratitude:{title:"Give Thanks",verse:"O give thanks unto the LORD; for he is good: for his mercy endureth for ever.",reference:"Psalm 136:1",message:"Notice the quiet blessings God has placed around you today."}};
const dailyVerses=[{verse:"Trust in the LORD with all thine heart; and lean not unto thine own understanding.",reference:"Proverbs 3:5"},{verse:"God is our refuge and strength, a very present help in trouble.",reference:"Psalm 46:1"},{verse:"The LORD is my shepherd; I shall not want.",reference:"Psalm 23:1"},{verse:"Be still, and know that I am God.",reference:"Psalm 46:10"},{verse:"I can do all things through Christ which strengtheneth me.",reference:"Philippians 4:13"}];
const bookSelect=document.getElementById("bookSelect"),chapterSelect=document.getElementById("chapterSelect");
document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));b.classList.add("active");showPage(b.dataset.page)}));
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById(id).classList.add("active");document.getElementById("sidebar").classList.remove("open");window.scrollTo({top:0,behavior:"smooth"})}
document.getElementById("menuButton").onclick=()=>document.getElementById("sidebar").classList.toggle("open");
document.getElementById("themeButton").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("xyhimeTheme",document.body.classList.contains("dark")?"dark":"light")};if(localStorage.getItem("xyhimeTheme")==="dark")document.body.classList.add("dark");
function buildBooks(){books.forEach(([name,,testament])=>{let o=document.createElement("option");o.value=name;o.textContent=name;bookSelect.appendChild(o);let b=document.createElement("button");b.className="book-button";b.textContent=name;b.onclick=()=>openBook(name);document.getElementById(testament==="old"?"oldBooks":"newBooks").appendChild(b)});updateChapters()}
function updateChapters(){chapterSelect.innerHTML="";let b=books.find(x=>x[0]===bookSelect.value);if(!b)return;for(let i=1;i<=b[1];i++){let o=document.createElement("option");o.value=i;o.textContent="Chapter "+i;chapterSelect.appendChild(o)}}bookSelect.addEventListener("change",updateChapters);
async function fetchBook(book){if(loadedBooks[book])return loadedBooks[book];let f=fileNames[book]||book;let r=await fetch(DATA_URL+f+".json");if(!r.ok)throw new Error("Could not load "+book);return loadedBooks[book]=await r.json()}
async function openBook(book){currentBook=book;currentChapter=1;bookSelect.value=book;updateChapters();chapterSelect.value=1;showPage("read");await loadChapter()}
function openBible(){showPage("read");loadChapter()}
async function loadChapter(){currentBook=bookSelect.value;currentChapter=Number(chapterSelect.value);let c=document.getElementById("verses");c.innerHTML='<p class="loading">Loading '+currentBook+" "+currentChapter+"…</p>";document.getElementById("chapterTitle").textContent=currentBook+" "+currentChapter;try{let d=await fetchBook(currentBook);let ch=d.chapters.find(x=>Number(x.chapter)===currentChapter);c.innerHTML="";if(!ch)throw new Error("Chapter unavailable");ch.verses.forEach(v=>{let p=document.createElement("p");p.className="verse";p.innerHTML='<span class="verse-number">'+v.verse+'</span>'+escapeHTML(v.text)+' <button class="save-verse" title="Save verse">♡</button>';p.querySelector("button").onclick=()=>addFavorite(v.text,currentBook+" "+currentChapter+":"+v.verse);c.appendChild(p)});localStorage.setItem("xyhimeLastReading",JSON.stringify({book:currentBook,chapter:currentChapter}))}catch(e){c.innerHTML='<div class="saved-card"><strong>Scripture could not load.</strong><p>Please check your internet connection and try again.</p></div>';console.error(e)}}
function syncReader(){bookSelect.value=currentBook;updateChapters();chapterSelect.value=currentChapter;loadChapter()}
function nextChapter(){let i=books.findIndex(x=>x[0]===currentBook);if(currentChapter<books[i][1])currentChapter++;else if(i<books.length-1){currentBook=books[i+1][0];currentChapter=1}syncReader()}
function previousChapter(){let i=books.findIndex(x=>x[0]===currentBook);if(currentChapter>1)currentChapter--;else if(i>0){currentBook=books[i-1][0];currentChapter=books[i-1][1]}syncReader()}
function continueReading(){let s=JSON.parse(localStorage.getItem("xyhimeLastReading")||"null");if(s){currentBook=s.book;currentChapter=s.chapter}showPage("read");syncReader()}
function loadDailyVerse(){let day=Math.floor(Date.now()/86400000);currentDailyVerse=dailyVerses[day%dailyVerses.length];document.getElementById("dailyVerse").textContent="“"+currentDailyVerse.verse+"”";document.getElementById("dailyReference").textContent=currentDailyVerse.reference}
function favoriteDailyVerse(){addFavorite(currentDailyVerse.verse,currentDailyVerse.reference)}function copyDailyVerse(){navigator.clipboard.writeText(currentDailyVerse.verse+" — "+currentDailyVerse.reference);alert("Verse copied 💜")}
function addFavorite(verse,reference){let a=JSON.parse(localStorage.getItem("xyhimeFavorites")||"[]");if(!a.some(x=>x.reference===reference))a.push({verse,reference});localStorage.setItem("xyhimeFavorites",JSON.stringify(a));renderFavorites();alert("Saved to Xyhime's favorites 💜")}
function renderFavorites(){let c=document.getElementById("favoriteList"),a=JSON.parse(localStorage.getItem("xyhimeFavorites")||"[]");c.innerHTML=a.length?a.map((x,i)=>'<div class="saved-card"><strong>'+escapeHTML(x.reference)+'</strong><p>“'+escapeHTML(x.verse)+'”</p><button onclick="removeFavorite('+i+')">Remove</button></div>').join(""):'<div class="saved-card">No favorite verses yet.</div>'}
function removeFavorite(i){let a=JSON.parse(localStorage.getItem("xyhimeFavorites")||"[]");a.splice(i,1);localStorage.setItem("xyhimeFavorites",JSON.stringify(a));renderFavorites()}
function openEmotion(t){showPage("encouragement");showEncouragement(t)}function showEncouragement(t){let d=encouragements[t];document.getElementById("encouragementResult").innerHTML='<div class="daily-card"><div class="card-label">A WORD FOR XYHIME</div><h2>'+d.title+'</h2><blockquote>“'+d.verse+'”</blockquote><strong>'+d.reference+'</strong><p>'+d.message+'</p></div>'}
async function searchBible(){let q=document.getElementById("searchInput").value.trim(),c=document.getElementById("searchResults");if(!q)return;let m=q.match(/^(.+?)\s+(\d+):(\d+)$/);if(m){let b=books.find(x=>x[0].toLowerCase()===m[1].toLowerCase());if(b){let d=await fetchBook(b[0]),ch=d.chapters.find(x=>Number(x.chapter)===Number(m[2])),v=ch&&ch.verses.find(x=>Number(x.verse)===Number(m[3]));c.innerHTML=v?'<div class="result-card"><strong>'+b[0]+" "+m[2]+":"+m[3]+'</strong><p>“'+escapeHTML(v.text)+'”</p></div>':'<div class="saved-card">Reference not found.</div>';return}}c.innerHTML='<div class="saved-card"><strong>Reference search is ready.</strong><p>Try a reference such as John 3:16. Full word-and-phrase search across all 31,000+ verses is planned for the next version.</p></div>'}
function saveNote(){saveJournalItem("xyhimeNotes","noteTitle","noteText");renderJournal("xyhimeNotes","notesList")}function savePrayer(){saveJournalItem("xyhimePrayers","prayerTitle","prayerText");renderJournal("xyhimePrayers","prayerList")}
function saveJournalItem(k,t,x){let ti=document.getElementById(t),tx=document.getElementById(x);if(!tx.value.trim())return;let a=JSON.parse(localStorage.getItem(k)||"[]");a.unshift({title:ti.value||"Untitled",text:tx.value,date:new Date().toLocaleDateString()});localStorage.setItem(k,JSON.stringify(a));ti.value="";tx.value=""}
function renderJournal(k,id){let a=JSON.parse(localStorage.getItem(k)||"[]");document.getElementById(id).innerHTML=a.map(x=>'<div class="saved-card"><small>'+x.date+'</small><h3>'+escapeHTML(x.title)+'</h3><p>'+escapeHTML(x.text)+'</p></div>').join("")}
function escapeHTML(v){let d=document.createElement("div");d.textContent=String(v);return d.innerHTML}
buildBooks();loadDailyVerse();renderFavorites();renderJournal("xyhimeNotes","notesList");renderJournal("xyhimePrayers","prayerList");loadChapter();